name: .NET Core + Webpack

on:
  push:
    branches: [ principal ]
    
  workflow_dispatch:
  
jobs:
  build-front:
    strategy:
      matrix:
        node-version: [14.x]    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM packages        
        run: npm install
        working-directory: ./FrontEnd
      - name: Publish frontend        
        run: npm run publish --if-present
        working-directory: ./FrontEnd 