name: Webpack + S3

on:
  push:
    branches: [ principal ]
    
  workflow_dispatch:
  
jobs:
  build-front:
    strategy:
      matrix:
        node-version: [14.x]    
    runs-on: ubuntu-latest    
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM packages        
        run: npm install
        working-directory: ./FrontEnd
      - name: Publish frontend        
        run: npm run publish --if-present
        working-directory: ./FrontEnd
      - name: "Configure AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: $AWS_ACCESS_KEY_ID
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: us-east-2
          mask-aws-account-id: false  
