name: "Build BackEnd & FrontEnd"

on:
  push:
    branches: [ principal ]
    
  workflow_dispatch:
  
jobs:
  build-BackEnd:
     runs-on: ubuntu-latest     
     steps:     
     - uses: actions/checkout@v2
     - name: Setup .NET Core
       uses: actions/setup-dotnet@v1
       with:
         dotnet-version: 5.0.100         
     #- name: Install dependencies       
     #  run: dotnet restore
     #  working-directory: ./BackEnd
     #- name: Build
     #  run: dotnet build --configuration Release --no-restore
     #  working-directory: ./BackEnd
     - name: Build and Publish to dist folder
       run: dotnet publish --output dist     
       working-directory: ./BackEnd
     - uses: papeloto/action-zip@v1
       with:
          files: ./Backend/dist/
          recursive: false
          dest: ./BackEnd/result.zip
     - uses: actions/upload-artifact@v1
       with:
        name: ${{ "BackEnd_" + github.sha }}
        path: ./BackEnd/result.zip
     #- name: Configure AWS credentials
      # uses: aws-actions/configure-aws-credentials@v1
       #with:
        #  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws-region: us-east-2
     #- name: Copy files to S3 bucket
     #  working-directory: ./BackEnd
     #  run: |
     #     aws s3 sync ./FrontEnd/dist s3://super-googles
       
  build-FrontEnd:
    strategy:
      matrix:
        node-version: [14.x]    
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2        
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM packages        
        run: npm install
        working-directory: ./FrontEnd
      - name: Publish frontend        
        run: npm run publish --if-present
        working-directory: ./FrontEnd
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to S3 bucket
        run: |
          aws s3 sync ./FrontEnd/dist ${{ secrets.AWS_S3_FRONT_END_BUCKET }}
